---
title: "MA_CRC_RR3_building_ratings"
author: "ML"
date: "16 August 2018"
output: html_document
---

```{r setup, include=FALSE}
sessionInfo()
# R version 3.5.1 (2018-07-02)
# Platform: x86_64-apple-darwin15.6.0 (64-bit)
# Running under: macOS Sierra 10.12.6

knitr::opts_chunk$set(echo = TRUE)
options(scipen=100)
pacman::p_load(tidyverse, rotl, ape, dplyr, tidyr, rotl, fulltext, metafor, car, robumeta, ggplot2, ggpubr, colourpicker, Rmisc)
```

```{r load data} 
dat <- read.csv("Activity3_EUI_Comparison_ML_v5.csv")
dim(dat)
names(dat)
str(dat)

### subset only the roes selected for meta-analysis
table(dat$use_for_MA) # 6 rows to be used for meta-analysis (yes)
dat <- dplyr::filter(dat, use_for_MA == "yes") 
dim(dat) 
dat <- droplevels(dat) 
str(dat)
```


```{r calculate ES} 
names(dat)

#for building-weighted EUI:
lnRR_EUI <- escalc(measure = "ROM", n1i = dat$NCB_N, n2i = dat$CB_N, m1i = dat$NCB_EUI_mean, 
    m2 = dat$CB_EUI_mean, sd1i = dat$NCB_EUI_SD, sd2i = dat$CB_EUI_SD, var.names	= c("lnRR_EUI", "VlnRR_EUI"))
lnRR_EUI # 5 ES available


#for area(gsf)-weighted	 EUI:
lnRR_EUI_area <- escalc(measure = "ROM", n1i = dat$NCB_N, n2i = dat$CB_N, m1i = dat$NCB_EUI_area_mean, 
    m2 = dat$CB_EUI_area_mean, sd1i = dat$NCB_EUI_area_SD, sd2i = dat$CB_EUI_area_SD, var.names	= c("lnRR_EUI_area", "VlnRR_EUI_area"))
lnRR_EUI_area # 4 ES available

dat <- bind_cols(dat, lnRR_EUI, lnRR_EUI_area)
dat

write.csv(dat, file = "MA_data_lnRR.csv", row.names = FALSE)
```

################################ 1 - main analysis ################################

```{r MA fixed-effect models} 
#dat <- read.csv(file = "MA_data_lnRR.csv")
names(dat)

# MA for building-weighted EUI:
fixed_lnRR_EUI <- rma(yi = lnRR_EUI, vi = VlnRR_EUI, method = "FE", data = dat)
summary(fixed_lnRR_EUI)
#estimate      se    zval    pval    ci.lb   ci.ub   
# 0.1013  0.0110  9.2264  <.0001  0.0798  0.1228  ***
(exp(summary(fixed_lnRR_EUI)[[1]])-1)*100 #10.6% more efficent, ns
forest(fixed_lnRR_EUI, slab=dat$study_ID)
#save(fixed_lnRR_EUI,file = "fixed_lnRR_EUI.Rdata")

# MA for area(gsf)-weighted	 EUI:
fixed_lnRR_EUI_area <- rma(yi = lnRR_EUI_area, vi = VlnRR_EUI_area, method = "FE", data = dat)
summary(fixed_lnRR_EUI_area)
# estimate      se    zval    pval    ci.lb   ci.ub   
# -0.0080  0.0110  -0.7271  0.4672  -0.0294  0.0135   
(exp(summary(fixed_lnRR_EUI_area)[[1]])-1)*100 #0.8% less efficent, ns
forest(fixed_lnRR_EUI_area, slab=dat$study_ID)
#save(fixed_lnRR_EUI_area,file = "fixed_lnRR_EUI_area.Rdata")
```

```{r MA random-effects models} 
# MA for building-weighted EUI:
random_lnRR_EUI <- rma(yi = lnRR_EUI, vi = VlnRR_EUI, method = "REML", data = dat)
summary(random_lnRR_EUI)
#I^2 (total heterogeneity / total variability):   97.75%
#H^2 (total variability / sampling variability):  44.4
#Test for Heterogeneity: 
#Q(df = 4) = 240.1464, p-val < .0001
#estimate      se    zval    pval    ci.lb   ci.ub   
#  0.2097  0.1251  1.6769  0.0936  -0.0354  0.4548 . 
(exp(summary(random_lnRR_EUI)[[1]])-1)*100 #23.3% more efficent, ns
forest(random_lnRR_EUI, slab=dat$study_ID)
#save(random_lnRR_EUI,file = "random_lnRR_EUI.Rdata")

#robust metafor
#robust_lnRR_EUI <- robust(random_lnRR_EUI, cluster  =  dat$study_ID)
#summary(robust_lnRR_EUI)
# estimate      se    tval    pval    ci.lb   ci.ub   
#   0.2097  0.1194  1.7555  0.1540  -0.1220  0.5413 


# MA for area(gsf)-weighted	 EUI:
random_lnRR_EUI_area <- rma(yi = lnRR_EUI_area, vi = VlnRR_EUI_area, method = "REML", data = dat)
summary(random_lnRR_EUI_area)
# estimate      se    zval    pval    ci.lb   ci.ub   
#   0.0022  0.0258  0.0854  0.9319  -0.0485  0.0529 
(exp(summary(random_lnRR_EUI_area)[[1]])-1)*100 #0.22% more efficent, ns
forest(random_lnRR_EUI_area, slab=dat$study_ID)
#save(random_lnRR_EUI_area,file = "random_lnRR_EUI_area.Rdata")

#robust metafor
#robust_lnRR_EUI_area <- robust(random_lnRR_EUI_area, cluster  =  dat$study_ID)
#summary(robust_lnRR_EUI_area)
# estimate      se    tval    pval    ci.lb   ci.ub   
#  0.0022  0.0239  0.0922  0.9323  -0.0740  0.0784 
```


```{r plots for report - fixed and random effects models} 
pdf(file="Fig_MA_fixed_random.pdf",width=10,height=8,pointsize=11)

par(mfcol=c(2,1)) 
par(mar=c(4,4,1,2))

# building-weighted EUI
res <- random_lnRR_EUI
forest(res, xlab="Log Ratio of Means [lnRR]", mlab="Random-effects Model", psize=1, slab=dat$study_ID) #main forest plot
# text(-4.1, -, pos=4, cex=1.1, bquote(paste("RE Model for All Studies (Q = ",
#      .(formatC(res$QE, digits=2, format="f")), ", df = ", .(res$k - res$p),
#      ", p = ", .(formatC(res$QEp, digits=2, format="f")), "; ", I^2, " = ",
#      .(formatC(res$I2, digits=1, format="f")), "%)"))) # add text with Q-value, dfs, p-value, and I^2 statistic
text(-13.5, -1.6, pos=4, cex=1, bquote(paste("(Q = ",
     .(formatC(res$QE, digits=2, format="f")), ", df = ", .(res$k - res$p),
     ", p = ", .(formatC(res$QEp, digits=2, format="f")), "; ", I^2, " = ",
     .(formatC(res$I2, digits=1, format="f")), "%)"))) # add text with Q-value, dfs, p-value, and I^2 statistic
addpoly(fixed_lnRR_EUI, row=-0.5, cex=1, mlab="Fixed-effect Model") # add summary polygon for the random model
text(-13.5, 7,  "A. Building-weighted total EUI comparisons", cex=1.2, pos=4, font=2)

# area-weighted EUI
res <- random_lnRR_EUI_area
forest(res, xlab="Log Ratio of Means [lnRR]", mlab="Random-effects Model", psize=1, slab=dat$study_ID) #main forest plot
# text(-4.1, -, pos=4, cex=1.1, bquote(paste("RE Model for All Studies (Q = ",
#      .(formatC(res$QE, digits=2, format="f")), ", df = ", .(res$k - res$p),
#      ", p = ", .(formatC(res$QEp, digits=2, format="f")), "; ", I^2, " = ",
#      .(formatC(res$I2, digits=1, format="f")), "%)"))) # add text with Q-value, dfs, p-value, and I^2 statistic
text(-5.6, -1.6, pos=4, cex=1, bquote(paste("(Q = ",
     .(formatC(res$QE, digits=2, format="f")), ", df = ", .(res$k - res$p),
     ", p = ", .(formatC(res$QEp, digits=2, format="f")), "; ", I^2, " = ",
     .(formatC(res$I2, digits=1, format="f")), "%)"))) # add text with Q-value, dfs, p-value, and I^2 statistic
addpoly(fixed_lnRR_EUI_area, row=-0.5, cex=1, mlab="Fixed-effect Model") # add summary polygon for the random model
text(-5.6, 6,  "B. Area-weighted total EUI comparisons", cex=1.2, pos=4, font=2)

dev.off()
```


```{r plots for report - dataset} 
#dat <- read.csv(file = "MA_data_lnRR.csv")

#number of buildings per group
dat %>% dplyr::select(study_ID, CB_N, NCB_N) %>% tidyr::gather(group, N, CB_N, NCB_N) -> dat_N
#total area of buildings per group
dat %>% dplyr::select(study_ID, CB_total_area, NCB_total_area) %>% tidyr::gather(group, total_area, CB_total_area, NCB_total_area) -> dat_total_area
#EUI_mean of buildings per group
dat %>% dplyr::select(study_ID, CB_EUI_mean, NCB_EUI_mean) %>% tidyr::gather(group, EUI_mean, CB_EUI_mean, NCB_EUI_mean) -> dat_EUI_mean
#EUI_SD of buildings per group
dat %>% dplyr::select(study_ID, CB_EUI_SD, NCB_EUI_SD) %>% tidyr::gather(group, EUI_SD, CB_EUI_SD, NCB_EUI_SD) -> dat_EUI_SD
#EUI_area_mean of buildings per group
dat %>% dplyr::select(study_ID, CB_EUI_area_mean, NCB_EUI_area_mean) %>% tidyr::gather(group, EUI_area_mean, CB_EUI_area_mean, NCB_EUI_area_mean) -> dat_EUI_area_mean
#EUI_area_SD of buildings per group
dat %>% dplyr::select(study_ID, CB_EUI_area_SD, NCB_EUI_area_SD) %>% tidyr::gather(group, EUI_area_SD, CB_EUI_area_SD, NCB_EUI_area_SD) -> dat_EUI_area_SD
#bind
dat_group <- dplyr::bind_cols(dat_N, dat_total_area, dat_EUI_mean, dat_EUI_SD, dat_EUI_area_mean, dat_EUI_area_SD)
#remove redundant columns
dat_group %>% dplyr::select(study_ID, group, N, total_area, EUI_mean, EUI_SD, EUI_area_mean, EUI_area_SD) -> dat_group
#rename levels, by name
dat_group$group <- factor(dat_group$group)
levels(dat_group$group) <- list(certified = "CB_N", comparison = "NCB_N")


### PLOTS

pdf(file="Fig_summary_data.pdf",width=6,height=12,pointsize=11)

theme_set(theme_pubclean())

# #bar plot of number of buildings
# p <- ggplot(dat_group, aes(x = study_ID, y = N)) +
#   geom_bar(
#     aes(color = group, fill = group),
#     stat = "identity", position = position_dodge(0.8),
#     width = 0.7
#     ) +
#   scale_color_manual(values = c("#66CDAA", "#EFC000FF"))+
#   scale_fill_manual(values = c("#66CDAA", "#EFC000FF"))
# p
# p + theme(axis.text.x = element_text(size=12, angle=270)) + theme(legend.title=element_blank()) + scale_x_discrete(name="") + scale_y_continuous(name="Number of buildings")

#bar plot of total floor area / number of buildings
p1 <- ggplot(dat_group, aes(x = study_ID, y = total_area/N)) +
  geom_bar(
    aes(color = group, fill = group),
    stat = "identity", position = position_dodge(0.8),
    width = 0.7
    ) +
  scale_color_manual(values = c("#66CDAA", "#EFC000FF")) +
  scale_fill_manual(values = c("#66CDAA", "#EFC000FF")) +
  theme(axis.text.x = element_text(size=12, angle=270)) +
  theme(legend.title=element_blank()) +
  theme(legend.justification = "top") +
  scale_x_discrete(name="", labels=NULL) +
  scale_y_continuous(name="Average building size [ft2]") +
  ggtitle("A.  Average building sizes")

#box plots of building-weighted EUI
p2 <- ggplot(dat_group, aes(x = study_ID, color = group)) +
  geom_pointrange(aes(y = EUI_mean, ymax = EUI_mean + EUI_SD, ymin = EUI_mean - EUI_SD),
                position = position_dodge(0.8)) +
  scale_color_manual(values = c("#66CDAA", "#EFC000FF")) +
  scale_fill_manual(values = c("#66CDAA", "#EFC000FF")) +
  theme(legend.position="none") +
  theme(legend.title=element_blank()) +
  scale_x_discrete(name="", labels=NULL) +
  ggtitle("B.  Building-weighted EUI") +
  scale_y_continuous(name="Building-weighted EUI [kBtu/ft2/year]")

#box plots of area-weigted EUI
p3 <- ggplot(dat_group, aes(x = study_ID, color = group)) +
  geom_pointrange(aes(y = EUI_area_mean, ymax = EUI_area_mean + EUI_area_SD, ymin = EUI_area_mean - EUI_area_SD),
                position = position_dodge(0.8)) +
  scale_color_manual(values = c("#66CDAA", "#EFC000FF")) +
  scale_fill_manual(values = c("#66CDAA", "#EFC000FF")) +
  theme(axis.text.x = element_text(size=12, angle=270)) +
  theme(legend.title=element_blank()) +
  theme(legend.position="none") +
  theme(legend.title=element_blank()) +
  scale_x_discrete(name="") +
  scale_y_continuous(name="Area-weighted EUI [kBtu/ft2/year]") +
    ggtitle("C.  Area-weighted EUI") +
  geom_text(aes(label = N, y = -30), position = position_dodge(0.1), vjust = 0)

multiplot(p1, p2, p3, cols=1)

dev.off()

#NOTE: plot needs tidying up in Adobe Illustrator

```

################################ 2 - alternative analysis ################################
# excluding study by Menassa_2012

```{r load data exclude Menassa_2012} 
#dat <- read.csv(file = "MA_data_lnRR.csv")
dat2 <- dplyr::filter(dat, study_ID != "Menassa_2012") 
dim(dat2) #5
dat2 <- droplevels(dat2) 
str(dat2)
```

```{r MA fixed-effects models without Menassa_2012} 
names(dat2)

# MA for building-weighted EUI:
fixed_lnRR_EUI_extra <- rma(yi = lnRR_EUI, vi = VlnRR_EUI, method = "FE", data = dat2)
summary(fixed_lnRR_EUI_extra)
#estimate      se    zval    pval    ci.lb   ci.ub   
# 0.1013  0.0110  9.2250  <.0001  0.0798  0.1228  ***
(exp(summary(fixed_lnRR_EUI_extra)[[1]])-1)*100 #10.7% more efficent, ns
forest(fixed_lnRR_EUI_extra, slab=dat2$study_ID)
#save(fixed_lnRR_EUI_extra,file = "fixed_lnRR_EUI_extra.Rdata")

# MA for area(gsf)-weighted	 EUI:
fixed_lnRR_EUI_area_extra <- rma(yi = lnRR_EUI_area, vi = VlnRR_EUI_area, method = "FE", data = dat2)
summary(fixed_lnRR_EUI_area_extra)
# estimate      se    zval    pval    ci.lb   ci.ub   
# -0.0081  0.0110  -0.7359  0.4618  -0.0295  0.0134  
(exp(summary(fixed_lnRR_EUI_area_extra)[[1]])-1)*100 #0.17% more efficent, ns
forest(fixed_lnRR_EUI_area_extra, slab=dat2$study_ID)
#save(fixed_lnRR_EUI_area_extra,file = "fixed_lnRR_EUI_area_extra.Rdata")

## overall v.similar results to these with Menassa_2012
```

```{r MA random-effects models without Menassa_2012} 
# MA for building-weighted EUI:
random_lnRR_EUI_extra <- rma(yi = lnRR_EUI, vi = VlnRR_EUI, method = "REML", data = dat2)
summary(random_lnRR_EUI_extra)
#estimate      se    zval    pval    ci.lb   ci.ub   
#  0.2082  0.1256  1.6575  0.0974  -0.0380  0.4544 
(exp(summary(random_lnRR_EUI_extra)[[1]])-1)*100 #23.1% more efficent, ns
forest(random_lnRR_EUI_extra, slab=dat2$study_ID)
#save(random_lnRR_EUI_extra,file = "random_lnRR_EUI_extra.Rdata")

#robust metafor
#robust_lnRR_EUI_extra <- robust(random_lnRR_EUI_extra, cluster  =  dat2$study_ID)
#summary(robust_lnRR_EUI_extra)
# estimate      se    tval    pval    ci.lb   ci.ub   
#    0.2082  0.1238  1.6820  0.1912  -0.1857  0.6021 


# MA for area(gsf)-weighted	 EUI:
random_lnRR_EUI_area_extra <- rma(yi = lnRR_EUI_area, vi = VlnRR_EUI_area, method = "REML", data = dat2)
summary(random_lnRR_EUI_area_extra)
# estimate      se    zval    pval    ci.lb   ci.ub   
#   0.0017  0.0259  0.0650  0.9482  -0.0490  0.0524   
(exp(summary(random_lnRR_EUI_area_extra)[[1]])-1)*100 #0.17% more efficent, ns
forest(random_lnRR_EUI_area_extra, slab=dat2$study_ID)
#save(random_lnRR_EUI_area_extra,file = "random_lnRR_EUI_area_extra.Rdata")

#robust metafor
#robust_lnRR_EUI_area_extra <- robust(random_lnRR_EUI_area_extra, cluster  =  dat2$study_ID)
#summary(robust_lnRR_EUI_area_extra)
# estimate      se    tval    pval    ci.lb   ci.ub   
#  0.0022  0.0239  0.0922  0.9323  -0.0740  0.0784 

#overall v.similar results to these with Menassa_2012
```


################################ 3 - alternative analysis ################################
# with multiple effect sizes per study

```{r load data larger subset} 
dat <- read.csv("Activity3_EUI_Comparison_ML_v5.csv")
dim(dat)

### subset only the rows selected for 2nd meta-analysis
dat3 <- dplyr::filter(dat, use_for_MA2 == "yes") 
dim(dat3) #13
dat3 <- droplevels(dat3) 
str(dat3)
```


```{r calculate ES with N adjusted for multiple comparisons} 
names(dat3)

#for building-weighted EUI:
lnRR_EUI <- escalc(measure = "ROM", n1i = dat3$NCB_N2, n2i = dat3$CB_N2, m1i = dat3$NCB_EUI_mean, 
    m2 = dat3$CB_EUI_mean, sd1i = dat3$NCB_EUI_SD, sd2i = dat3$CB_EUI_SD, var.names	= c("lnRR_EUI", "VlnRR_EUI"))
lnRR_EUI


#for area(gsf)-weighted	 EUI:
lnRR_EUI_area <- escalc(measure = "ROM", n1i = dat3$NCB_N2, n2i = dat3$CB_N2, m1i = dat3$NCB_EUI_area_mean, 
    m2 = dat3$CB_EUI_area_mean, sd1i = dat3$NCB_EUI_area_SD, sd2i = dat3$CB_EUI_area_SD, var.names	= c("lnRR_EUI_area", "VlnRR_EUI_area"))
lnRR_EUI_area


dat3 <- bind_cols(dat3, lnRR_EUI, lnRR_EUI_area)
dat3

write.csv(dat3,file = "MA_data_lnRR2.csv", row.names = FALSE)
```


```{r MA fixed-effects models adjusted for multiple comparisons} 

# MA for building-weighted EUI:
fixed_lnRR_EUI <- rma.mv(yi = lnRR_EUI, V = VlnRR_EUI, method = "FE", data = dat3)
summary(fixed_lnRR_EUI)
#estimate      se    zval    pval    ci.lb   ci.ub   
# 0.0906  0.0117  7.7228  <.0001  0.0676  0.1136  ***
(exp(summary(fixed_lnRR_EUI)[[1]])-1)*100 #9.5% more efficent
forest(fixed_lnRR_EUI, slab=dat3$study_ID)


# MA for area(gsf)-weighted	 EUI:
fixed_lnRR_EUI_area <- rma.mv(yi = lnRR_EUI_area, V = VlnRR_EUI_area, method = "FE", data = dat3)
summary(fixed_lnRR_EUI_area)
# estimate      se    zval    pval    ci.lb   ci.ub   
# -0.0210  0.0117  -1.8056  0.0710  -0.0439  0.0018  .
(exp(summary(fixed_lnRR_EUI_area)[[1]])-1)*100 #2.1% less efficent, ns
forest(fixed_lnRR_EUI_area, slab=dat3$study_ID)
```


```{r MA random-effects models adjusted for multiple comparisons} 

# MA for building-weighted EUI:
random_lnRR_EUI <- rma.mv(yi = lnRR_EUI, V = VlnRR_EUI, random=list(~1|study_ID), method = "REML", data = dat3)
summary(random_lnRR_EUI)
#(df = 11) = 334.9719, p-val < .0001
#estimate      se    zval    pval    ci.lb   ci.ub   
#   0.1763  0.1160  1.5198  0.2032  -0.1457  0.4983 
(exp(summary(random_lnRR_EUI)[[1]])-1)*100 #19.27% more efficent, ns
forest(random_lnRR_EUI, slab=dat3$study_ID)

#robust metafor
#robust_lnRR_EUI <- robust(random_lnRR_EUI, cluster  =  dat3$study_ID)
#summary(robust_lnRR_EUI)
# estimate      se    tval    pval    ci.lb   ci.ub   
# 0.1763  0.1160  1.5198  0.2032  -0.1457  0.4983


# MA for area(gsf)-weighted	 EUI:
random_lnRR_EUI_area <- rma.mv(yi = lnRR_EUI_area, V = VlnRR_EUI_area, random=list(~1|study_ID), method = "REML", data = dat3)
summary(random_lnRR_EUI_area)
# estimate      se    zval    pval    ci.lb   ci.ub   
#   -0.0069  0.0326  -0.2128  0.8315  -0.0708  0.0569 
(exp(summary(random_lnRR_EUI_area)[[1]])-1)*100 #0.7% less efficent, ns
forest(random_lnRR_EUI_area, slab=dat3$study_ID)

#robust metafor
#robust_lnRR_EUI_area <- robust(random_lnRR_EUI_area, cluster  =  dat3$study_ID)
#summary(robust_lnRR_EUI_area)
# estimate      se    tval    pval    ci.lb   ci.ub   
# -0.0069  0.0305  -0.2274  0.8347  -0.1039  0.0901  
```
